[project]
name = "reranker-server"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "litserve>=0.2.19",
    "protobuf>=7.36.2",
    "python-dotenv>=1.2.3",
    "sentencepiece>=0.2.2",
    "torch>=2.14.0",
    "transformers>=5.17.0",
]
